// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8dc0580d-604f-4fbd-9992-3e7dc83c2146";

const char SSID[]               = "realme85g";    // Network SSID (name)
const char PASS[]               = "vedant12";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "q9?FVXjMSshVdUxplzd9E9Jla";    // Secret device password

void onStressLevelChange();
void onGSRChange();

String Stress_level;
int GSR;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(Stress_level, READWRITE, ON_CHANGE, onStressLevelChange);
  ArduinoCloud.addProperty(GSR, READWRITE, ON_CHANGE, onGSRChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
